
CREATE TABLE IF NOT EXISTS career_applications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ref_no TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    ic_number TEXT NOT NULL,
    date_of_birth TEXT,
    marital_status TEXT,
    race TEXT,
    religion TEXT,
    phone TEXT NOT NULL,
    email TEXT NOT NULL,
    address_line_1 TEXT,
    address_line_2 TEXT,
    address_postcode TEXT,
    address_city TEXT,
    address_state TEXT,
    bank_name TEXT,
    bank_account_name TEXT,
    bank_account_number TEXT,
    recruiter_name TEXT DEFAULT 'HQ JomConsult',
    photo_data TEXT,
    ic_front_data TEXT,
    ic_back_data TEXT,
    selfie_ic_data TEXT,
    status TEXT DEFAULT 'BARU',
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
